baseURL = "https://kubah.bangunan.co/"
languageCode = "id"
title = "Kubah Masjid | Jual & Jasa Pemasangan Kubah Masjid Enamel GRC Stainless Beton"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Distributor Kubah Masjid - Jual Kubah Masjid berbagai model seperti kubah enamel, kubah GRC, kubah stainless, dan kubah beton dengan harga terjangkau dan layanan pemasangan profesional."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual kubah masjid", "kubah enamel", "kubah GRC", "kubah stainless", "kubah beton", "pemasangan kubah masjid", "kubah masjid murah", "distributor kubah masjid"]
  base_price = 500000
  price_range = 200000
  free_shipping = true
  materials = [
  "Kubah Enamel",
  "Kubah GRC",
  "Kubah Stainless",
  "Kubah Beton",
  "Kubah Klasik",
  "Kubah Galvalum"
  ]
  categories = ["Kubah Masjid", "Kubah Enamel", "Kubah GRC", "Kubah Stainless", "Kubah Beton"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Kubah bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Kubah yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Distributor Kubah Masjid Berkualitas"
  hero_description = "Kami menjual kubah masjid berkualitas dengan berbagai pilihan seperti kubah enamel, kubah GRC, kubah stainless, dan kubah beton. Solusi ideal untuk masjid dengan desain yang estetik, tahan lama, dan kokoh."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Kubah Masjid"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan kubah masjid berkualitas tinggi dengan harga terjangkau, layanan pemasangan profesional, dan berbagai pilihan desain. Gratis konsultasi untuk membantu Anda memilih kubah yang sesuai dengan kebutuhan masjid atau musholla Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

[[params.footer_services]]
  text = "kubah.bangunan.co menjual berbagai pilihan kubah masjid seperti kubah enamel, kubah GRC, dan kubah beton. Produk kami tahan lama, estetis, dan harga terjangkau. Pilih kami untuk mempercantik dan memperkokoh masjid Anda dengan kubah terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya memesan kubah enamel dari kubah.bangunan.co dan hasilnya {sangat memuaskan|luar biasa|memenuhi harapan}. Proses pemasangannya {cepat|efisien|rapi} dan kubahnya {berkualitas tinggi|tahan lama|unggul}.|Layanan dari kubah.bangunan.co {sangat profesional|hebat|memuaskan} dengan kubah yang {berkualitas|handal} dan pemasangan yang {cepat|efisien} dan rapi.}"
  response = "{Terima kasih atas kepercayaan Anda! Kami senang dapat menyediakan kubah {berkualitas|terbaik} untuk {masjid|proyek} Anda.|Kami sangat menghargai kepercayaan Anda}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{kubah.bangunan.co sangat {membantu|mempermudah} dalam memilih kubah masjid untuk {proyek|konstruksi} masjid kami. Produk yang kami beli {berkualitas|hebat} dan sesuai dengan {kebutuhan|ekspektasi|rencana}.|Saya {sangat puas|terkesan} dengan bantuan dari kubah.bangunan.co dalam memilih kubah yang {tepat|cocok} untuk masjid kami.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan kubah masjid dari kami.|Terima kasih atas ulasannya, kami senang dapat memenuhi harapan Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Produk kubah GRC dari kubah.bangunan.co {sangat berkualitas|unggul|hebat} dan cocok untuk {proyek|konstruksi} masjid di {tempat|lokasi} saya. Proses pembelian dan pengirimannya juga {cepat|efisien|aman}.|Saya {sangat puas|terkesan} dengan kubah GRC dari kubah.bangunan.co. Proses pembelian dan pengirimannya {sangat cepat|mudah} dan hasilnya {luar biasa|hebat}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan kubah masjid {berkualitas|terbaik} dengan {layanan terbaik|pelayanan prima}.|Kami sangat senang mendengar bahwa Anda puas dengan hasil kubah dari kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan kubah beton dari kubah.bangunan.co. {Kualitas|Mutu} kubahnya {sangat baik|hebat|unggul} dan tahan lama untuk {proyek|konstruksi} masjid kami.|Kubah beton dari kubah.bangunan.co {berkualitas|handal|kokoh} dan pemasangannya {cepat|efisien|rapi} sesuai kebutuhan proyek kami.}"
  response = "{Senang mendengar Anda puas dengan kubah kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan kubah.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Kubah GRC yang saya {pesan|dapatkan} {sangat berkualitas|berkualitas tinggi|handal} dan sesuai dengan {harapan|ekspektasi|rencana} saya.|Saya {senang|terkesan|puas} dengan pelayanan dari kubah.bangunan.co. Kubahnya {berkualitas|tahan lama|modern} dan sesuai dengan keinginan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda mewujudkan proyek masjid dengan kubah terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Kubah masjid dari kubah.bangunan.co sangat {sesuai|tepat|cocok} dengan kebutuhan {proyek|renovasi|konstruksi} masjid kami. Proses pengirimannya {cepat|aman|efisien} dan {terjamin|rapi|bersih}.|Saya {puas|terkesan|senang} dengan kubah dari kubah.bangunan.co. Layanan pengirimannya {profesional|cepat|teratur} dan sesuai dengan kebutuhan proyek kami.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan produk kubah kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Kubah Enamel"
  price = "1.500.000 /unit"
[[params.tabelItems]]
  name = "Kubah GRC"
  price = "1.750.000 /unit"
[[params.tabelItems]]
  name = "Kubah Stainless"
  price = "2.000.000 /unit"
[[params.tabelItems]]
  name = "Kubah Beton"
  price = "1.000.000 /unit"
[[params.tabelItems]]
  name = "Kubah Klasik"
  price = "1.800.000 /unit"
[[params.tabelItems]]
  name = "Kubah Galvalum"
  price = "1.900.000 /unit"

[params.appliList]
  "Kubah Enamel" = "masjid, bangunan umum"
  "Kubah GRC" = "masjid, bangunan komersial"
  "Kubah Stainless" = "masjid, area outdoor"
  "Kubah Beton" = "masjid, bangunan permanen"
  "Kubah Klasik" = "masjid, bangunan bersejarah"
  "Kubah Galvalum" = "masjid, arsitektur kontemporer"

[params.kegunaanList]
  "Kubah Enamel" = "cocok untuk memberikan estetika indah pada masjid"
  "Kubah GRC" = "digunakan untuk keawetan dan kekuatan struktur"
  "Kubah Stainless" = "cocok untuk ketahanan terhadap cuaca dan korosi"
  "Kubah Beton" = "digunakan untuk bangunan permanen dan tahan lama"
  "Kubah Klasik" = "memberikan kesan tradisional dan bersejarah"
  "Kubah Galvalum" = "cocok untuk desain arsitektur kontemporer"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Distributor Kubah Masjid Enamel, GRC, Stainless & Beton | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"